<<<<<<< HEAD
// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11.08.2024, 09:52:53
const configMerger = require("C:/Users/New/Documents/GitHub/eori-main/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");
=======
// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11.08.2024, 09:18:43
const configMerger = require("D:/git/eori-main/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");
>>>>>>> d70d0e99c8ecb221cc742291809f2b685f001c72

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/git/eori-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/git/eori-main/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/git/eori-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/git/eori-main/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/git/eori-main/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/git/eori-main/plugins/**/*.{js,ts,mjs}","D:/git/eori-main/composables/**/*.{js,ts,mjs}","D:/git/eori-main/utils/**/*.{js,ts,mjs}","D:/git/eori-main/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/git/eori-main/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/git/eori-main/app.config.{js,ts,mjs}"] }));

module.exports = config
